package com.livingtools.manager;

import com.livingtools.LivingToolsPlugin;
import com.livingtools.abilities.Ability;
import com.livingtools.abilities.AbilityRegistry;
import org.bukkit.ChatColor;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class WikiGenerator {

    public static void generateWiki() {
        File wikiFile = new File(LivingToolsPlugin.getInstance().getDataFolder(), "WIKI.md");
        try (FileWriter writer = new FileWriter(wikiFile)) {
            writer.write("# Living Tools Wiki\n\n");
            writer.write(
                    "Welcome to the official documentation for Living Tools. This file is auto-generated based on the current server configuration.\n\n");

            // --- Abilities ---
            writer.write("## Abilities\n");
            writer.write("Living Tools gain abilities as they level up or through special infusions.\n\n");
            writer.write("| Ability | Description | Type | Cooldown |\n");
            writer.write("| :--- | :--- | :--- | :--- |\n");

            List<Ability> abilities = new ArrayList<>(AbilityRegistry.getAbilities().values());
            abilities.sort(Comparator.comparing(Ability::getName));

            for (Ability ability : abilities) {
                String name = ChatColor.stripColor(ability.getName());
                String desc = ChatColor.stripColor(ability.getDescription());
                String type = ability.getType().name();
                String cooldown = ability.getCooldown() > 0 ? ability.getCooldown() + "s" : "Passive";

                writer.write("| **" + name + "** | " + desc + " | " + type + " | " + cooldown + " |\n");
            }

            // --- Commands ---
            writer.write("\n## Commands\n");
            writer.write("- `/livingtool help` - Show help menu.\n");
            writer.write("- `/livingtool stats` - View tool stats.\n");
            writer.write("- `/livingtool top` - View leaderboard.\n");
            writer.write("- `/livingtool recipes` - View crafting recipes.\n");
            writer.write("- `/livingtool trade <player> <price>` - Trade a tool securely.\n");
            writer.write("- `/livingtool admin menu` - Open Admin GUI.\n");

            // --- Configuration ---
            writer.write("\n## Configuration\n");
            writer.write("Current key settings from `config.yml`:\n\n");
            writer.write("- **XP Scaling**: " + ConfigManager.getInt("xp.level-scaling") + "\n");
            writer.write("- **Mining Multiplier**: " + ConfigManager.getMiningXPMultiplier() + "x\n");
            writer.write("- **Combat Multiplier**: " + ConfigManager.getCombatXPMultiplier() + "x\n");
            writer.write(
                    "- **Boss Kills**: " + (ConfigManager.getBoolean("discord.events.boss-kill") ? "Discord Alerts ON"
                            : "Discord Alerts OFF") + "\n");

            writer.write("\n---\n");
            writer.write("*Generated by LivingTools Wiki Generator*");

            LivingToolsPlugin.getInstance().getLogger().info("WIKI.md generated successfully!");

        } catch (IOException e) {
            LivingToolsPlugin.getInstance().getLogger().severe("Failed to generate WIKI.md: " + e.getMessage());
        }
    }
}
